version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/circleci-test
    steps:
      - checkout
      - save_cache:
          key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-test
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Adding NPM authentication token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: npm run lint:report
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Testing
          command: npm run test:report
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage

  build:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Creating Build
          command: npm run build
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install System Dependecies
          working_directory: /
          command: sudo apt-get -y -qq update
      - run:
          name: Install System Dependecies
          command: sudo apt update && sudo apt install python-pip python-dev
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - setup_remote_docker
      - run:
          name: Deploying
          command: docker ps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
         requires:
           - dependencies
      - build:
         type: approval
         requires:
           - dependencies
         filters:
           branches:
             only:
               - master
               - develop
               - /release-.*/
               - /hotfix-.*/
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /release-.*/
                - /hotfix-.*/
