version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - checkout
      - run:
          name: Create Checkout Hash File
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repo-cache-{{ checksum ".circle-sha" }}
          paths:
            - ~/circleci-test

  bundle_dependecies:
    docker:
      - image: node:6
    working_directory: ~/circleci-test
    steps:
      - run:
          name: Create Checkout Hash File
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-cache-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependecy-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: node:6
    working_directory: ~/circleci-test
    steps:
      - run:
          name: Create Checkout Hash File
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-cache-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint

  build:
    docker:
      - image: node:6
    working_directory: ~/circleci-test
    steps:
      - run:
          name: Create Checkout Hash File
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-cache-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Build
          command: npm run build
      - save_cache:
          key: build-cache-{{ checksum ".circle-sha" }}
          paths:
            - dist

  deploy:
    docker:
      - image: node:6
    working_directory: ~/circleci-test
    steps:
      - run:
          name: Create Checkout Hash File
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-cache-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: build-cache-{{ checksum ".circle-sha" }}
      - run:
          name: Run Deploy
          command: pwd

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - bundle_dependecies:
          requires:
            - checkout_code
      - test:
          requires:
            - bundle_dependecies
      - build:
          requires:
            - bundle_dependecies
            - checkout_code
          filters:
            branches:
              only:
                - /release-.*/
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
#                - master
#                - develop
                - /release-.*/
#                - /hotfix-.*/

