version: 2
jobs:
  bundle_dependecies:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - checkout
      - save_cache:
          key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-test
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Adding NPM authentication token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: npm run lint2
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Testing
          command: npm run test:ci
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Creating Build
          command: npm run build
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:8.4.0
    working_directory: ~/circleci-test
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploying
          command: pwd

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - bundle_dependecies
      - lint:
          requires:
            - bundle_dependecies
      - test:
          requires:
            - bundle_dependecies
      - build:
          requires:
            - bundle_dependecies
          filters:
            branches:
              only:
                - master
                - develop
                - /release-.*/
                - /hotfix-.*/
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /release-.*/
                - /hotfix-.*/

